#!/bin/bash
# Redirect output to log file for debugging
exec >> /databricks/driver/init-script.log 2>&1
set -x  # Print commands as they’re run

# Update the package index
apt-get update

# Install Tesseract OCR and Poppler utilities
apt-get install -y tesseract-ocr poppler-utils





databricks fs cp /Volumes/watech_aid_edp_sh/cluster_config/config_sh_files/stacycluster.sh dbfs:/databricks/init-scripts/stacycluster.sh




dbfs:/databricks/init-scripts/stacycluster.sh
